workflows:
  ios-build:
    name: iOS Build
    cache_paths:
      - ios/Pods
      - ios/Podfile.lock
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
