// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11qJryvsRJ3lTetyxzJBEHSPg_CcWYQQ',
    appId: '1:292822995515:web:77d923f0af86e61978821e',
    messagingSenderId: '292822995515',
    projectId: 'viewtodonate-e5a16',
    authDomain: 'viewtodonate-e5a16.firebaseapp.com',
    storageBucket: 'viewtodonate-e5a16.appspot.com',
    measurementId: 'G-D35X4H3RWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIs0_WSmjrnAfOLHo7qRAdpKaxF_JZ0ps',
    appId: '1:292822995515:android:34f8a4e89e2c241a78821e',
    messagingSenderId: '292822995515',
    projectId: 'viewtodonate-e5a16',
    storageBucket: 'viewtodonate-e5a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZUusbRLFJr2zFYDpPlH6nfR61eLX2mkM',
    appId: '1:292822995515:ios:3fd05d2841c3204d78821e',
    messagingSenderId: '292822995515',
    projectId: 'viewtodonate-e5a16',
    storageBucket: 'viewtodonate-e5a16.appspot.com',
    iosBundleId: 'com.example.viewToDonate',
  );

}