name: iOS Build

on:
  push:
    branches:
      - master  
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - run: flutter pub get
      - run: flutter build ios --no-codesign
